%YAML:1.0
---
nb_camera: 2 
camera_0: # all the calibration parameters (intrinsic/extrinsic) for the camera 0
   camera_matrix: !!opencv-matrix # 3x3 intrinsic matrix
      rows: 3
      cols: 3
      dt: d
      data: [ 1065.19, 0., 1099.76, 0., 1065.28, 621.531, 0., 0., 1. ]
   distortion_vector: !!opencv-matrix # 1x5 distortion vector (Brown model here)
      rows: 1
      cols: 5
      dt: d
      data: [ -0.0535795, 0.0263845, -0.000309893, -8.31882e-05, -0.0108287 ]
   distortion_type: 0 # type of distortion model (0: perspective, 1: fisheye)
camera_1: # all the calibration parameters (intrinsic/extrinsic) for the camera 1
   camera_matrix: !!opencv-matrix # 3x3 intrinsic matrix for camera 1
      rows: 3
      cols: 3
      dt: d
      data: [ 1062.48, 0., 1105.71, 0., 1062.49, 608.373, 0., 0., 1. ]
   distortion_vector: !!opencv-matrix # 1x4 distortion vector (fisheye model)
      rows: 1
      cols: 5
      dt: d
      data: [ -0.0519472, 0.023429, -0.000345647, -0.000301131, -0.00914485 ]
   distortion_type: 0 # type of distortion model (0: perspective, 1: fisheye)