%YAML:1.0
---
nb_camera: 2 
camera_0: # all the calibration parameters (intrinsic/extrinsic) for the camera 0
   camera_matrix: !!opencv-matrix # 3x3 intrinsic matrix
      rows: 3
      cols: 3
      dt: d
      data: [ 1068.55, 0., 1122.4, 0., 1068.74, 632.579, 0., 0., 1. ]
   distortion_vector: !!opencv-matrix # 1x5 distortion vector (Brown model here)
      rows: 1
      cols: 5
      dt: d
      data: [ -0.0530216, 0.025668, 0.000143909, -0.000337566, -0.0100711 ]
   distortion_type: 0 # type of distortion model (0: perspective, 1: fisheye)
camera_1: # all the calibration parameters (intrinsic/extrinsic) for the camera 1
   camera_matrix: !!opencv-matrix # 3x3 intrinsic matrix for camera 1
      rows: 3
      cols: 3
      dt: d
      data: [ 1066.17, 0., 1097.88, 0., 1066.72, 613.349, 0., 0., 1. ]
   distortion_vector: !!opencv-matrix # 1x4 distortion vector (fisheye model)
      rows: 1
      cols: 5
      dt: d
      data: [ -0.0476521, 0.0212008, -4.48125e-05, -0.000737505, -0.00895334 ]
   distortion_type: 0 # type of distortion model (0: perspective, 1: fisheye)